server:
  port: 8081

logging:
  file:
    name: /Users/rmoguluri/logs/retail-product-service.log
  level:
    root: INFO
    org:
      hibernate: INFO

spring:
  datasource:
    url: jdbc:mysql://retail-products.cnpr9ukaae9u.us-east-1.rds.amazonaws.com:3306/PRODUCTS_DB
    username: products
    password: Target123$